# Generated by Django 3.1.14 on 2022-04-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conv',
            fields=[
                ('conv_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.conv')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_rel', to='conv_dep.word')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.relation')),
                ('tail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail_rel', to='conv_dep.word')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_id', models.IntegerField()),
                ('word', models.CharField(max_length=64)),
                ('conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.conv')),
            ],
            options={
                'ordering': ['utr_id'],
                'unique_together': {('conv', 'utr_id')},
            },
        ),
    ]
