# Generated by Django 3.1.14 on 2022-04-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convs',
            fields=[
                ('convId', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utterances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.convs')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('utrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.utterances')),
            ],
        ),
        migrations.CreateModel(
            name='ConvRels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headWordId', models.ManyToManyField(related_name='head_rel_set', to='conv_dep.Words')),
                ('relationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.relations')),
                ('tailWordId', models.ManyToManyField(related_name='tail_rel_set', to='conv_dep.Words')),
            ],
        ),
    ]
