# Generated by Django 3.1.14 on 2022-04-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Convs',
            new_name='Conv',
        ),
        migrations.RenameModel(
            old_name='ConvRels',
            new_name='ConvRel',
        ),
        migrations.RenameModel(
            old_name='Relations',
            new_name='Relation',
        ),
        migrations.RenameModel(
            old_name='Utterances',
            new_name='Utterance',
        ),
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
