# Generated by Django 3.1.14 on 2022-04-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterances',
            name='items',
            field=models.TextField(max_length=2048),
        ),
        migrations.CreateModel(
            name='UtrsIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utrsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.utterances')),
            ],
        ),
    ]
