# Generated by Django 3.1.14 on 2022-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='tag',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
