# Generated by Django 3.1.14 on 2022-08-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0002_relation_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='conv',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='relation',
        ),
        migrations.AlterUniqueTogether(
            name='utterance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='utterance',
            name='conv',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='Conv',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='Utterance',
        ),
    ]
