# Generated by Django 3.1.14 on 2022-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0002_auto_20220429_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
