# Generated by Django 3.1.14 on 2022-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0002_auto_20220428_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='color',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConvRel',
        ),
    ]
