# Generated by Django 3.1.14 on 2022-04-28 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0003_auto_20220428_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headWordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_rel', to='conv_dep.word')),
                ('relationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.relation')),
                ('tailWordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail_rel', to='conv_dep.word')),
            ],
        ),
    ]
