# Generated by Django 3.1.14 on 2022-04-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0003_auto_20220429_2135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utterance',
            unique_together={('conv', 'utr_id', 'word_id')},
        ),
    ]
