# Generated by Django 3.1.14 on 2022-04-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0004_convrel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvRel',
        ),
    ]
