# Generated by Django 3.1.14 on 2022-08-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0004_conv_relation_relationship_utterance_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utterance',
        ),
    ]
