# Generated by Django 3.1.14 on 2022-05-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0004_auto_20220429_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utterance',
            options={'ordering': ['conv', 'utr_id', 'word_id']},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='head',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tail',
            field=models.CharField(max_length=8),
        ),
    ]
