# Generated by Django 3.1.14 on 2022-05-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0005_auto_20220503_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='conv',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
