# Generated by Django 3.1.14 on 2022-04-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0006_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='relation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='headWordId',
            new_name='headWord',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='relationId',
            new_name='relation',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='tailWordId',
            new_name='tailWord',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='utrId',
            new_name='utr',
        ),
    ]
