# Generated by Django 3.1.14 on 2022-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0006_conv_tagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conv',
            name='tagged',
        ),
        migrations.AddField(
            model_name='conv',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
