# Generated by Django 3.1.14 on 2022-04-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0007_auto_20220428_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='headWord',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='tailWord',
            new_name='tail',
        ),
    ]
