# Generated by Django 3.1.14 on 2022-04-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0008_auto_20220428_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='utr',
        ),
    ]
