# Generated by Django 3.1.14 on 2022-04-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0009_remove_word_utr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utr_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.utterance')),
                ('wordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conv_dep.word')),
            ],
        ),
    ]
