# Generated by Django 3.1.14 on 2022-04-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conv_dep', '0010_utr_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utr_word',
            old_name='utrId',
            new_name='utr',
        ),
        migrations.RenameField(
            model_name='utr_word',
            old_name='wordId',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='utterance',
            old_name='convId',
            new_name='conv',
        ),
    ]
