# Generated by Django 3.1.14 on 2022-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220617_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processassignment',
            name='item_id',
            field=models.BigIntegerField(verbose_name='Item ID'),
        ),
    ]
